const app = document.querySelector('#app');

const characters = [
  { id:'bouquet', name:'贝壳小羊·花束', type:'温柔陪伴型', image:'assets/lamb-bouquet.png', color:'#c9a877', quote:'“今天也想把好心情送给你。”', traits:['温柔','细心','治愈','可靠'], intro:'贝壳小羊总会记得你随口说过的小事。它不擅长轰轰烈烈，却会在每一个普通日子里，为你留下温柔的花香。' },
  { id:'wave', name:'贝壳小羊·元气', type:'明亮探索型', image:'assets/lamb-wave.png', color:'#7da6bd', quote:'“走吧，今天也有新的惊喜！”', traits:['乐观','勇敢','热情','自由'], intro:'贝壳小羊相信生活要有一点冲动和很多笑声。和它一起，你会发现转角的风、天空的云，都藏着值得出发的理由。' },
  { id:'shy', name:'贝壳小羊·害羞', type:'慢热守护型', image:'assets/lamb-shy.png', color:'#ca9b9e', quote:'“我会慢一点，但一直都在。”', traits:['真诚','敏感','专一','体贴'], intro:'贝壳小羊的话不多，心意却很满。它会认真听你说完每一句话，也会把无法说出口的关心，悄悄放在你身边。' },
  { id:'walk', name:'贝壳小羊·旅行', type:'自在冒险型', image:'assets/lamb-walk.png', color:'#a598c1', quote:'“把日常装进口袋，一起出发吧。”', traits:['好奇','松弛','浪漫','独立'], intro:'贝壳小羊带着轻轻的行囊和大大的好奇心。它想陪你把平凡的小路走成故事，把每一次相遇都珍藏起来。' }
];

const questions = [
  { title:'第一次相遇', sub:'命运的交汇点', scene:'微风刚好，阳光也刚好。你和小羊在一间有花香的咖啡店门口相遇。', say:'“你好呀……今天风有点凉，你穿得够不够暖？如果冷的话，我的围巾可以借给你。”', opts:[['主动关心对方，让对方感到温暖',[3,1,1]],['先观察，找到合适时机再靠近',[1,0,2]],['邀请 TA 一起去做有趣的事',[1,3,0]],['安静等待，看看对方会不会先注意到你',[0,1,3]]] },
  { title:'雨天的伞', sub:'靠近一点点', scene:'天空忽然飘起细雨，小羊把伞往你这边偏了偏。', say:'“伞有一点小，不过我们靠近一点，也不会淋湿。”', opts:[['把伞再推向 TA，自己淋一点也没关系',[3,1,1]],['自然地和 TA 并肩走，聊聊喜欢的天气',[2,2,1]],['提议去附近躲雨，顺便喝杯热饮',[1,3,1]],['礼貌地保持距离，不想给 TA 添麻烦',[0,0,3]]] },
  { title:'晚安消息', sub:'心事的回音', scene:'深夜，你收到一条消息：“今天有一点累，不过想到你就好多了。”', say:'“不用马上回复也没关系，我只是想让你知道。”', opts:[['认真问问发生了什么，陪 TA 把话说完',[3,1,2]],['发一个可爱的表情和一句晚安',[1,3,1]],['分享自己的小故事，逗 TA 开心',[2,3,0]],['提醒 TA 好好休息，明天再聊',[1,0,3]]] },
  { title:'周末邀约', sub:'一起去远方', scene:'周末空出来了，小羊拿着一张写满小店的地图朝你眨眼。', say:'“今天想和你去一个没去过的地方。”', opts:[['先问 TA 最想去哪里，让 TA 做主',[2,1,2]],['马上答应，随机选一条路出发',[1,3,0]],['提前规划路线，把一切安排好',[1,1,3]],['建议找一个安静的地方慢慢待着',[3,0,2]]] },
  { title:'小小误会', sub:'把话说开', scene:'因为一句没及时回复的消息，你们之间安静了一会儿。', say:'“是不是我哪里做得不够好？我想听听你的感受。”', opts:[['坦诚说出自己的感受，也认真倾听',[3,2,3]],['先给 TA 一点空间，等情绪平静',[1,0,3]],['用轻松的玩笑打破沉默',[1,3,0]],['悄悄准备一份小礼物表达歉意',[2,1,1]]] },
  { title:'秘密花园', sub:'交换心事', scene:'傍晚的花园很安静，小羊说它有一个小秘密想告诉你。', say:'“我有一点紧张，但我相信你。”', opts:[['告诉 TA：你的心事在我这里很安全',[3,1,3]],['也分享一个自己的小秘密',[2,2,1]],['牵牵 TA 的手，不急着说话',[3,0,2]],['认真分析 TA 的烦恼，帮它想办法',[1,1,3]]] },
  { title:'意外惊喜', sub:'被记住的瞬间', scene:'你发现小羊为你准备了一个小惊喜，正躲在角落观察你的反应。', say:'“我记得你说过喜欢这个，希望你会开心。”', opts:[['马上拥抱 TA，认真表达感谢',[3,3,1]],['告诉 TA 自己被这份细心打动了',[3,1,2]],['也开始盘算回赠一份惊喜',[2,3,1]],['小心收好礼物，默默珍藏这份心意',[1,0,3]]] },
  { title:'星光约定', sub:'把未来写下来', scene:'夜色很深，星星落在安静的湖面。小羊轻轻问你：“以后，也一起走吗？”', say:'“不需要回答得很快，我会陪你慢慢想。”', opts:[['坚定地说：想和你一起经历很多以后',[3,2,3]],['笑着说：那就从明天开始吧',[2,3,1]],['和 TA 一起列一张未来愿望清单',[2,2,3]],['靠在 TA 身边，用行动给出回答',[3,1,2]]] }
];

const lessons = [
  { topic:'第一课：程序的入口', prompt:'想使用 cout 输出内容时，需要包含哪个头文件？', code:'#include <span class="accent">&lt;iostream&gt;</span>\nusing namespace std;\n\nint main() {\n  cout &lt;&lt; "你好，小羊！";\n  return 0;\n}', options:['&lt;iostream&gt;','&lt;math&gt;','&lt;vector&gt;','&lt;file&gt;'], correct:0, explain:'iostream 提供了 cout 与 cin。写好 #include &lt;iostream&gt;，程序才能使用输入输出工具。' },
  { topic:'第二课：main 函数', prompt:'C++ 程序从哪里开始执行？', code:'#include &lt;iostream&gt;\nusing namespace std;\n\n<span class="accent">int main()</span> {\n  return 0;\n}', options:['从 main() 开始','从第一行注释开始','从 cout 开始','从 return 开始'], correct:0, explain:'main() 是 C++ 程序的入口。操作系统会先找到它，再一行行执行其中的语句。' },
  { topic:'第三课：输出', prompt:'下面哪一行会在屏幕上输出“心动”？', code:'cout &lt;&lt; <span class="accent">"心动"</span>;', options:['cout &lt;&lt; "心动";','cin &gt;&gt; "心动";','int 心动;','return "心动";'], correct:0, explain:'cout 表示“向控制台输出”，<< 把右边的内容送到屏幕上。字符串要用英文双引号包起来。' },
  { topic:'第四课：输入', prompt:'想把用户输入的年龄保存到 age，应该使用哪一行？', code:'int age;\n<span class="accent">cin &gt;&gt; age;</span>', options:['cin >> age;','cout << age;','age == cin;','int cin = age;'], correct:0, explain:'cin 用来从键盘读取数据，>> 表示把输入存入右边的变量。' },
  { topic:'第五课：变量', prompt:'哪一个变量适合保存“相遇的天数”这种整数？', code:'<span class="accent">int days</span> = 8;\ncout &lt;&lt; days;', options:['int days = 8;','double days = "8";','string days = 8;','bool days = 8;'], correct:0, explain:'int 用来保存整数，例如 8、-3、2026。变量名 days 让代码的意思更容易看懂。' },
  { topic:'第六课：条件判断', prompt:'当 score 大于等于 60 时，应该使用哪个条件？', code:'if (<span class="accent">score &gt;= 60</span>) {\n  cout &lt;&lt; "通过";\n}', options:['score >= 60','score = 60','score != 60','score ++ 60'], correct:0, explain:'>= 的意思是“大于或等于”。注意 = 是赋值，== 才是判断是否相等。' },
  { topic:'第七课：循环', prompt:'想让“加油！”输出 3 次，循环条件应写成什么？', code:'for (int i = 0; <span class="accent">i &lt; 3</span>; i++) {\n  cout &lt;&lt; "加油！";\n}', options:['i < 3','i = 3','i > 3','i == 3'], correct:0, explain:'i 从 0 开始，每次加 1；只要 i < 3，就会执行，共执行 0、1、2 三次。' },
  { topic:'第八课：函数返回值', prompt:'这个函数想返回两数之和，空格处应该填什么？', code:'int add(int a, int b) {\n  <span class="accent">return a + b;</span>\n}', options:['return a + b;','cout a + b;','int a + b;','cin >> a + b;'], correct:0, explain:'return 会把函数计算出的结果交回给调用它的地方。因为 add 的返回类型是 int，所以要返回一个整数。' }
];

let state = { screen:'home', character:null, step:0, scores:[0,0,0], phase:'story', learned:0, feedback:null };
const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render() { const fns = { home, choose, profile, game, result }; app.innerHTML = fns[state.screen](); app.querySelectorAll('[data-action]').forEach(el => el.addEventListener('click', act)); }
function actionButton(label, action, extra='primary') { return `<button class="${extra}" data-action="${action}">${label}</button>`; }
function home() { return `<section class="screen hero"><div class="brand-strip"><div class="brand-unit"><img src="assets/gongxing-qingyun.jpg" alt="躬行青耘标识"/><span>躬行青耘</span></div><div class="brand-divider"></div><div class="brand-unit"><img class="school-logo" src="assets/hohhot-no2-wordmark.svg" alt="呼和浩特二中标识"/><span>呼和浩特市<br>第二中学</span></div></div><div class="hero-content"><img class="art" src="assets/lamb-wave.png" alt="挥手的贝壳小羊"/><h1>和贝壳小羊开启一场心动</h1><p class="lead">贝壳小羊的四种可爱模样，八段轻轻的心动。<br>在互动剧情中学习 C++，把每一次选择<br>都变成一段小小的代码冒险。</p><p class="tagline">一场只属于你和贝壳小羊的心动故事。</p>${actionButton('开始旅程','choose')}<p class="footnote">C++ 基础语法 · 无需注册 · 即刻开始</p></div></section>`; }
function choose() { return `<section class="screen"><div class="top-copy"><h2>选择贝壳小羊的模样</h2><p>每一面贝壳小羊，都有属于自己的温柔</p></div><div class="character-grid">${characters.map(c => `<button class="character" style="--accent:${c.color}" data-action="select:${c.id}"><img src="${c.image}" alt="${c.name}"/><h3>${c.name}</h3><span class="pill">${c.type}</span><p>${c.quote}</p></button>`).join('')}</div></section>`; }
function profile() { const c = state.character; return `<section class="screen profile" style="--accent:${c.color}"><button class="back" data-action="choose">← 返回选择</button><img class="profile-art" src="${c.image}" alt="${c.name}"/><h2>${c.name}</h2><div class="traits">${c.traits.map(t=>`<span>${t}</span>`).join('')}</div><p class="forecast">心动预告</p><p style="line-height:1.65;margin:12px 0 15px">一段恰到好处的相遇。${c.type.replace('型','')}的 TA，正带着自己的方式慢慢靠近你。</p><article class="intro-card">${c.intro}</article><p class="quote">${c.quote}</p>${actionButton('确认选择 TA','start')}</section>`; }
function game() { if (state.phase === 'lesson') return study(); if (state.phase === 'feedback') return feedback(); const q = questions[state.step], n = state.step + 1; return `<section class="screen game"><div class="progress-row"><span class="step">${n}</span><div class="track"><b style="width:${n/8*100}%"></b></div><span>8</span></div><div class="chapter"><div class="icon">✦</div><div class="eyebrow">CHAPTER ${n} OF 8</div><h2>${q.title}</h2><strong>${q.sub}</strong></div><p class="scene">${q.scene}</p><div class="dialogue">${q.say}</div><p class="choice-label">选择你的回应</p><div class="options">${q.opts.map((o,i)=>`<button class="option" data-action="answer:${i}"><span class="letter">${'ABCD'[i]}</span>${o[0]}</button>`).join('')}</div></section>`; }
function study() { const lesson=lessons[state.step], n=state.step+1; return `<section class="screen game"><div class="progress-row"><span class="step">${n}</span><div class="track"><b style="width:${n/8*100}%"></b></div><span>8</span></div><article class="study-card"><span class="learn-badge">🐑 小羊 C++ 小课堂 · ${n}/8</span><h2>${lesson.topic}</h2><pre class="cpp-code"><code>${lesson.code}</code></pre><p>${lesson.prompt}</p><div class="options lesson-options">${lesson.options.map((o,i)=>`<button class="option" data-action="study:${i}"><span class="letter">${'ABCD'[i]}</span><code>${o}</code></button>`).join('')}</div></article></section>`; }
function feedback() { const lesson=lessons[state.step], last=state.step===7, good=state.feedback; return `<section class="screen game"><article class="study-card feedback ${good?'good':'try'}"><div class="symbol">${good?'🎉':'💡'}</div><span class="learn-badge">C++ 学习反馈</span><h2>${good?'答对啦！':'差一点就答对了'}</h2><p>${lesson.explain}</p>${actionButton(last?'查看我的学习结局':'继续下一章','nextlesson')}</article></section>`; }
function result() { const [empathy, expression, stability] = state.scores; const total = empathy+expression+stability; const score = Math.min(96, 58 + Math.round(total/54*38)); const c = state.character; const persona = empathy >= expression && empathy >= stability ? '温柔共鸣型' : expression >= stability ? '明亮表达型' : '安心守护型'; const ending = score >= 78 ? '星光约定' : score >= 65 ? '被温柔围住' : '慢慢靠近的风'; return `<section class="screen result"><span class="status">💛 美好结局</span><div class="circle" style="--score:${score}"><b>${score}%</b></div><h2 class="match">心动合拍</h2><p>你们的相处方式</p><article class="result-card"><header>💛 你的心动人格</header><h2>${persona}</h2><span class="code">EMP · EXP · STEADY</span><p class="description">你愿意用自己的方式感受、回应与守护一段关系。你的温柔，会让相处变得更安心。</p>${metric('💛 情绪共鸣',empathy,16)}${metric('💬 情感表达',expression,16)}${metric('🏠 安定需求',stability,16)}</article><article class="result-card"><header>💻 你的 C++ 学习成就</header><h2>${state.learned} / 8</h2><span class="code">C++ STARTER</span><p class="description">你已完成 8 个 C++ 基础知识点：程序入口、输入输出、变量、判断、循环与函数。答对 ${state.learned} 题，继续保持好奇心！</p></article><article class="result-card partner"><header>🐑 你的伙伴</header><img src="${c.image}" alt="${c.name}"/><h3>${c.name}</h3><q>${c.quote}</q></article><article class="ending"><header>📖 最终结局</header><h3>💛 ${ending}</h3><p>${c.name}牵着你的手，在晚风里慢慢往前走。它说：“以后每一天，我都会在这里等你。不用说什么，只要你在，就够了。”</p><p>你们相视而笑，把今天的心意收进行囊，也把彼此写进了温柔的以后。</p></article><div class="actions">${actionButton('再测一次','restart')}${actionButton('选择其他小羊','choose','secondary')}</div></section>`; }
function metric(label, val, max) { const shown = Math.min(max, val); return `<div class="metric"><span>${label}</span><div class="bar"><i style="--width:${shown/max*100}%"></i></div><span>${val}/${max}</span></div>`; }
function act(event) { const action = event.currentTarget.dataset.action; if (action === 'choose') state.screen='choose'; else if (action === 'start' || action === 'restart') { state.step=0; state.scores=[0,0,0]; state.phase='story'; state.learned=0; state.feedback=null; state.screen='game'; } else if (action.startsWith('select:')) { state.character=characters.find(c=>c.id===action.split(':')[1]); state.screen='profile'; } else if (action.startsWith('answer:')) { const score=questions[state.step].opts[Number(action.split(':')[1])][1]; state.scores=state.scores.map((v,i)=>v+score[i]); state.phase='lesson'; } else if (action.startsWith('study:')) { state.feedback=Number(action.split(':')[1])===lessons[state.step].correct; if (state.feedback) state.learned += 1; state.phase='feedback'; } else if (action === 'nextlesson') { state.step += 1; state.phase='story'; state.screen=state.step===questions.length ? 'result' : 'game'; } render(); window.scrollTo({top:0,behavior:'smooth'}); }
render();
