const { characters, routes, questions, lessons, practices } = window.gameData;
const app = document.querySelector('#app');
const SAVE_KEY = 'beike-lamb-cpp-session-v3';
const PROFILE_KEY = 'beike-lamb-cpp-profile-v3';

const blankState = () => ({ screen:'home', characterId:null, step:0, scores:[0,0,0], phase:'story', learned:0, completedLessons:[], completedPractices:[], hint:false, feedback:null, practiceFeedback:null, sessionXP:0 });
const blankProfile = () => ({ xp:0, streak:0, lastStudyDate:'', correctTotal:0, completedChapters:0, badges:[] });
const today = () => new Date().toISOString().slice(0,10);
const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
const getJSON = (key, fallback) => { try { return { ...fallback(), ...JSON.parse(localStorage.getItem(key) || '{}') }; } catch { return fallback(); } };
let state = getJSON(SAVE_KEY, blankState);
let profile = getJSON(PROFILE_KEY, blankProfile);

function save() { localStorage.setItem(SAVE_KEY, JSON.stringify(state)); localStorage.setItem(PROFILE_KEY, JSON.stringify(profile)); }
function character() { return characters.find(item => item.id === state.characterId) || characters[0]; }
function routeKey() { const max = Math.max(...state.scores); return state.scores[0] === max ? 'warm' : state.scores[1] === max ? 'explore' : 'steady'; }
function route() { return routes[routeKey()]; }
function button(label, action, style='primary', extra='') { return `<button class="${style} ${extra}" data-action="${action}">${label}</button>`; }
function award(amount) { state.sessionXP += amount; profile.xp += amount; if (profile.lastStudyDate !== today()) { const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0,10); profile.streak = profile.lastStudyDate === yesterday ? profile.streak + 1 : 1; profile.lastStudyDate = today(); } refreshBadges(); }
function refreshBadges() { const add = (id, label, icon) => { if (!profile.badges.some(item => item.id === id)) profile.badges.push({ id, label, icon }); }; if (profile.xp >= 10) add('first-shell','第一片贝壳','🐚'); if (profile.correctTotal >= 8) add('syntax-explorer','语法探险家','💻'); if (profile.streak >= 7) add('seven-tides','七日海潮','🌊'); }
function resumeAvailable() { return Boolean(state.characterId && state.step < questions.length && state.screen !== 'result'); }

function render() { const views = { home, choose, profileView, game, result, report }; app.innerHTML = views[state.screen](); app.querySelectorAll('[data-action]').forEach(element => element.addEventListener('click', act)); save(); }

function brand() { return `<div class="brand-strip"><div class="brand-unit"><img src="assets/gongxing-qingyun.jpg" alt="躬行青耘标识"/><span>躬行青耘</span></div><div class="brand-divider"></div><div class="brand-unit"><img class="school-logo" src="assets/hohhot-no2-wordmark.svg" alt="呼和浩特二中标识"/><span>呼和浩特市<br>第二中学</span></div></div>`; }
function home() { const resume = resumeAvailable() ? button(`继续第 ${state.step + 1} 章`, 'resume') : button('开始旅程', 'choose'); return `<section class="screen hero">${brand()}<div class="hero-content"><div class="home-stats"><span>🔥 连续学习 ${profile.streak} 天</span><span>🐚 已收集 ${profile.xp} 枚贝壳</span></div><img class="art" src="assets/lamb-wave.png" alt="挥手的贝壳小羊"/><h1>和贝壳小羊开启一场心动</h1><p class="lead">贝壳小羊的四种可爱模样，八段轻轻的心动。<br>在互动剧情中学习 C++，把每一次选择<br>都变成一段小小的代码冒险。</p><p class="tagline">一场只属于你和贝壳小羊的心动故事。</p>${resume}<div class="home-actions">${button('查看学习档案', 'report', 'secondary')}</div><p class="footnote">C++ 基础语法 · 本机保存进度 · 无需注册</p></div></section>`; }
function choose() { return `<section class="screen"><div class="nav-row">${button('← 返回首页','home','text-button')}<span>🐚 ${profile.xp}</span></div><div class="top-copy"><h2>选择贝壳小羊的模样</h2><p>每一面贝壳小羊，都有属于自己的温柔</p></div><div class="character-grid">${characters.map(item => `<button class="character" style="--accent:${item.color}" data-action="select:${item.id}"><img loading="lazy" src="${item.image}" alt="${item.name}"/><h3>${item.name}</h3><span class="pill">${item.type}</span><p>${item.quote}</p></button>`).join('')}</div></section>`; }
function profileView() { const item = character(); return `<section class="screen profile" style="--accent:${item.color}"><button class="back" data-action="choose">← 返回选择</button><img class="profile-art" src="${item.image}" alt="${item.name}"/><h2>${item.name}</h2><div class="traits">${item.traits.map(trait => `<span>${trait}</span>`).join('')}</div><p class="forecast">心动预告</p><p style="line-height:1.65;margin:12px 0 15px">一段恰到好处的相遇。${item.type.replace('型','')}的 TA，正带着自己的方式慢慢靠近你。</p><article class="intro-card">${item.intro}</article><p class="quote">${item.quote}</p>${button('确认选择 TA','start')}</section>`; }
function progress(step = state.step + 1) { return `<div class="progress-row" aria-label="当前第 ${step} 章，共 8 章"><span class="step">${step}</span><div class="track"><b style="width:${step / questions.length * 100}%"></b></div><span>${questions.length}</span></div>`; }
function game() { if (state.phase === 'lesson') return lessonView(); if (state.phase === 'feedback') return feedbackView(); if (state.phase === 'practice') return practiceView(); const question = questions[state.step]; const line = route().lines[state.step]; return `<section class="screen game">${progress()}<div class="route-pill">${route().emoji} ${route().name}</div><div class="chapter"><div class="icon">✦</div><div class="eyebrow">CHAPTER ${state.step + 1} OF 8</div><h2>${question.title}</h2><strong>${question.sub}</strong></div><p class="scene">${question.scene}</p><p class="story-route">${line}</p><div class="dialogue">${question.say}</div><p class="choice-label">选择你的回应</p><div class="options">${question.opts.map((option,index) => `<button class="option" data-action="answer:${index}" aria-label="选项 ${'ABCD'[index]}：${option[0]}"><span class="letter">${'ABCD'[index]}</span>${option[0]}</button>`).join('')}</div></section>`; }
function lessonView() { const lesson = lessons[state.step]; return `<section class="screen game">${progress()}<article class="study-card"><span class="learn-badge">🐑 贝壳小羊 C++ 小课堂 · ${state.step + 1}/8</span><h2>${lesson.topic}</h2><pre class="cpp-code"><code>${lesson.code}</code></pre><p>${lesson.prompt}</p>${state.hint ? `<p class="hint">💡 ${lesson.hint}</p>` : ''}<div class="options lesson-options">${lesson.options.map((option,index) => `<button class="option" data-action="study:${index}"><span class="letter">${'ABCD'[index]}</span><code>${option}</code></button>`).join('')}</div><div class="lesson-actions">${button('查看提示','hint','secondary')}</div></article></section>`; }
function feedbackView() { const lesson = lessons[state.step]; const correct = state.feedback; const isLast = state.step === questions.length - 1; const primary = correct ? button(isLast ? '进入最终代码任务' : '继续下一章', 'nextlesson') : button('再试一次', 'retrylesson'); const skip = !correct ? button('先继续，我会回来复习', 'skiplesson', 'secondary') : ''; return `<section class="screen game">${progress()}<article class="study-card feedback ${correct ? 'good' : 'try'}"><div class="symbol">${correct ? '🎉' : '💡'}</div><span class="learn-badge">C++ 学习反馈</span><h2>${correct ? '答对啦！' : '差一点就答对了'}</h2><p>${lesson.explain}</p><div class="actions">${primary}${skip}</div></article></section>`; }
function practiceView() { const task = practices[state.step]; const feedback = state.practiceFeedback; return `<section class="screen game">${progress()}<article class="practice-card"><span class="learn-badge">💻 贝壳代码任务</span><h2>${task.title}</h2><p>${task.intro}</p><label class="editor-label" for="code-answer">补全空白处</label><div class="code-editor"><code>${esc(task.before)}</code><input id="code-answer" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="${esc(task.placeholder)}" value="${esc(state.practiceValue || '')}"/><code>${esc(task.after)}</code></div>${feedback ? `<p class="practice-feedback ${feedback.ok ? 'ok' : 'bad'}">${feedback.ok ? '✅ ' : '💡 '}${feedback.message}</p>` : `<p class="hint">提示：${task.hint}</p>`}<div class="actions">${feedback && feedback.ok ? button('领取贝壳，继续旅程','nextpractice') : button('运行代码','runpractice')}${feedback && !feedback.ok ? button('查看提示','practicehint','secondary') : ''}${button('暂时跳过','skippractice','secondary')}</div></article></section>`; }
function metric(label, value, max) { const shown = Math.min(max, value); return `<div class="metric"><span>${label}</span><div class="bar"><i style="--width:${shown / max * 100}%"></i></div><span>${value}/${max}</span></div>`; }
function result() { const [empathy, expression, stability] = state.scores; const score = Math.min(96, 58 + Math.round((empathy + expression + stability) / 54 * 38)); const item = character(); const currentRoute = route(); const persona = empathy >= expression && empathy >= stability ? '温柔共鸣型' : expression >= stability ? '明亮表达型' : '安心守护型'; const practiceCount = state.completedPractices.length; return `<section class="screen result"><span class="status">💛 美好结局</span><div class="circle" style="--score:${score}"><b>${score}%</b></div><h2 class="match">${currentRoute.name}</h2><p>${currentRoute.note}</p><article class="result-card"><header>💛 你的心动人格</header><h2>${persona}</h2><span class="code">EMP · EXP · STEADY</span><p class="description">你的选择让故事走向了独一无二的路线。每一次认真回应，都是在练习理解与表达。</p>${metric('💛 情绪共鸣',empathy,16)}${metric('💬 情感表达',expression,16)}${metric('🏠 安定需求',stability,16)}</article><article class="result-card"><header>💻 你的 C++ 学习成就</header><h2>${state.learned} / 8</h2><span class="code">C++ STARTER · ${practiceCount}/4 代码任务</span><p class="description">已掌握输入输出、变量、判断、循环与函数。你本次收集了 ${state.sessionXP} 枚贝壳；错题可以随时重练。</p></article><article class="result-card partner"><header>🐑 你的伙伴</header><img loading="lazy" src="${item.image}" alt="${item.name}"/><h3>${item.name}</h3><q>${item.quote}</q></article><article class="ending"><header>📖 最终结局</header><h3>${currentRoute.emoji} ${currentRoute.name}</h3><p>${currentRoute.lines[7]}</p><p>${item.name}牵着你的手说：“代码像一次次小小的选择，试过、改过，就会越来越接近想要的答案。”</p></article><div class="actions">${button('分享我的成就','share')}${button('导出学习报告','export','secondary')}${button('再测一次','restart','secondary')}${button('选择其他模样','choose','secondary')}</div></section>`; }
function report() { const badgeMarkup = profile.badges.length ? profile.badges.map(item => `<span class="badge">${item.icon} ${item.label}</span>`).join('') : '<p class="empty-note">完成一章学习后，就会在这里收到第一枚贝壳徽章。</p>'; return `<section class="screen report"><div class="nav-row">${button('← 返回首页','home','text-button')}<span>本机学习档案</span></div><div class="top-copy"><h2>贝壳学习档案</h2><p>只保存在这台设备，不上传个人信息</p></div><article class="result-card"><div class="report-stats"><div><b>${profile.xp}</b><span>贝壳</span></div><div><b>${profile.streak}</b><span>连续学习天数</span></div><div><b>${profile.correctTotal}</b><span>累计答对</span></div></div><p class="description">已完成最高章节：${profile.completedChapters} / 8。建议每天完成 1 个小任务，保持轻松而稳定的学习节奏。</p></article><article class="result-card"><header>🏆 已获得的徽章</header><div class="badge-grid">${badgeMarkup}</div></article><article class="result-card"><header>🧑‍🏫 教师/家长查看说明</header><p class="description">点击“导出学习报告”会下载一份本机文本报告，便于学生在课堂展示或交给老师；没有账号、班级和云端数据收集。</p></article><div class="actions">${button('导出学习报告','export')}${button('开始一轮新冒险','choose','secondary')}</div></section>`; }
function finishLesson() { if (practices[state.step]) { state.phase = 'practice'; state.practiceFeedback = null; state.practiceValue = ''; return; } advanceChapter(); }
function advanceChapter() { profile.completedChapters = Math.max(profile.completedChapters, state.step + 1); if (state.step >= questions.length - 1) { state.screen = 'result'; state.phase = 'story'; } else { state.step += 1; state.phase = 'story'; state.hint = false; state.feedback = null; } refreshBadges(); }
function exportReport() { const text = ['贝壳小羊 C++ 学习报告', `导出日期：${today()}`, `贝壳：${profile.xp}`, `连续学习：${profile.streak} 天`, `累计答对：${profile.correctTotal}`, `最高完成章节：${profile.completedChapters}/8`, `获得徽章：${profile.badges.map(item => item.label).join('、') || '暂无'}`, '', '说明：本报告只来自当前浏览器本机保存的数据。'].join('\n'); const url = URL.createObjectURL(new Blob([text], { type:'text/plain;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = '贝壳小羊-C++学习报告.txt'; link.click(); URL.revokeObjectURL(url); }
async function shareResult() { const shareData = { title:'贝壳小羊 C++ 心动学习', text:`我和贝壳小羊完成了 C++ 冒险，答对 ${state.learned}/8 题，收集了 ${state.sessionXP} 枚贝壳！`, url:location.href }; try { if (navigator.share) await navigator.share(shareData); else { await navigator.clipboard.writeText(`${shareData.text}\n${shareData.url}`); alert('成就文案和链接已复制，可以分享给朋友啦。'); } } catch {} }
function act(event) { const action = event.currentTarget.dataset.action; if (action === 'home') state.screen = 'home'; else if (action === 'choose') state.screen = 'choose'; else if (action === 'report') state.screen = 'report'; else if (action === 'resume') state.screen = 'game'; else if (action === 'start' || action === 'restart') { state = { ...blankState(), screen:'game', characterId:state.characterId }; } else if (action.startsWith('select:')) { state.characterId = action.split(':')[1]; state.screen = 'profileView'; } else if (action.startsWith('answer:')) { const score = questions[state.step].opts[Number(action.split(':')[1])][1]; state.scores = state.scores.map((value,index) => value + score[index]); state.phase = 'lesson'; state.hint = false; award(3); } else if (action === 'hint') state.hint = true; else if (action.startsWith('study:')) { const correct = Number(action.split(':')[1]) === lessons[state.step].correct; state.feedback = correct; if (correct && !state.completedLessons.includes(state.step)) { state.completedLessons.push(state.step); state.learned += 1; profile.correctTotal += 1; award(10); } state.phase = 'feedback'; } else if (action === 'retrylesson') { state.phase = 'lesson'; state.hint = true; } else if (action === 'skiplesson' || action === 'nextlesson') finishLesson(); else if (action === 'runpractice') { const input = document.querySelector('#code-answer'); const value = input ? input.value : ''; state.practiceValue = value; const task = practices[state.step]; state.practiceFeedback = task.check(value) ? { ok:true, message:task.success } : { ok:false, message:'还没有达到预期。请查看提示，再修改一次。' }; } else if (action === 'practicehint') state.practiceFeedback = { ok:false, message:practices[state.step].hint }; else if (action === 'nextpractice') { if (!state.completedPractices.includes(state.step)) { state.completedPractices.push(state.step); award(25); } advanceChapter(); } else if (action === 'skippractice') advanceChapter(); else if (action === 'export') exportReport(); else if (action === 'share') shareResult(); render(); if (!['export','share'].includes(action)) window.scrollTo({ top:0, behavior:'smooth' }); }
render();
